# Generated by Django 2.1 on 2019-10-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=1000)),
                ('csv_file', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('cc', models.CharField(max_length=1000)),
                ('bcc', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=20000)),
            ],
        ),
    ]
